import type { Company } from '@/types/company';

export const COMPANIES: Company[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    type: 'venture',
    sector: 'Fintech',
    stage: 'series-f-plus',
    hcGrowthPct: 24,
    valuation: 65,
    marketCap: null,
    cultureScore: 4.1,
    employeeCount: 7400,
    openRoles: 47,
    techStack: ['Ruby', 'Go', 'Scala', 'TypeScript'],
    investors: ['Sequoia', 'a16z', 'GV'],
    engBlogUrl: 'https://stripe.com/blog/engineering',
    lastRound: 'Series I · Mar 2021',
    location: 'San Francisco Bay Area',
    website: 'https://stripe.com',
  },
  {
    id: 'linear',
    name: 'Linear',
    type: 'venture',
    sector: 'Developer Tools',
    stage: 'series-c',
    hcGrowthPct: 31,
    valuation: 0.4,
    marketCap: null,
    cultureScore: 4.7,
    employeeCount: 90,
    openRoles: 12,
    techStack: ['TypeScript', 'Rust', 'GraphQL'],
    investors: ['Sequoia', 'Accel'],
    engBlogUrl: 'https://linear.app/blog',
    lastRound: 'Series C · Nov 2022',
    location: 'San Francisco Bay Area',
    website: 'https://linear.app',
  },
  {
    id: 'figma',
    name: 'Figma',
    type: 'venture',
    sector: 'Developer Tools',
    stage: 'series-f-plus',
    hcGrowthPct: 18,
    valuation: 12.5,
    marketCap: null,
    cultureScore: 4.4,
    employeeCount: 1100,
    openRoles: 23,
    techStack: ['C++', 'TypeScript', 'Rust', 'WebAssembly'],
    investors: ['a16z', 'Sequoia', 'Index Ventures'],
    engBlogUrl: 'https://www.figma.com/blog/section/engineering',
    lastRound: 'Series E · Jun 2021',
    location: 'San Francisco Bay Area',
    website: 'https://figma.com',
  },
  {
    id: 'anduril',
    name: 'Anduril Industries',
    type: 'venture',
    sector: 'Defense / Aerospace',
    stage: 'series-f-plus',
    hcGrowthPct: 8,
    valuation: 14,
    marketCap: null,
    cultureScore: 3.9,
    employeeCount: 3200,
    openRoles: 19,
    techStack: ['C++', 'Python', 'Rust'],
    investors: ['Andreessen Horowitz', 'Founders Fund', 'Valor Equity'],
    engBlogUrl: null,
    lastRound: 'Series F · Dec 2023',
    location: 'Los Angeles',
    website: 'https://anduril.com',
  },
  {
    id: 'klarna',
    name: 'Klarna',
    type: 'venture',
    sector: 'Fintech',
    stage: 'series-f-plus',
    hcGrowthPct: -12,
    valuation: 6.7,
    marketCap: null,
    cultureScore: 3.6,
    employeeCount: 3500,
    openRoles: 8,
    techStack: ['Java', 'Kotlin', 'Python'],
    investors: ['Sequoia', 'SoftBank', 'Silver Lake'],
    engBlogUrl: 'https://engineering.klarna.com',
    lastRound: 'Series B Extension · Jul 2022',
    location: 'New York City',
    website: 'https://klarna.com',
  },
  {
    id: 'notion',
    name: 'Notion',
    type: 'venture',
    sector: 'SaaS / Enterprise',
    stage: 'series-c',
    hcGrowthPct: 15,
    valuation: 10,
    marketCap: null,
    cultureScore: 4.2,
    employeeCount: 500,
    openRoles: 31,
    techStack: ['TypeScript', 'React', 'Rust'],
    investors: ['Sequoia', 'Index Ventures', 'Coatue'],
    engBlogUrl: 'https://www.notion.so/blog/topic/technology',
    lastRound: 'Series C · Oct 2021',
    location: 'San Francisco Bay Area',
    website: 'https://notion.so',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    type: 'venture',
    sector: 'AI / ML',
    stage: 'series-b',
    hcGrowthPct: 62,
    valuation: 6,
    marketCap: null,
    cultureScore: 4.5,
    employeeCount: 120,
    openRoles: 18,
    techStack: ['Python', 'C++', 'Triton', 'CUDA'],
    investors: ['Lightspeed', 'a16z', 'General Catalyst'],
    engBlogUrl: 'https://mistral.ai/news',
    lastRound: 'Series B · Jun 2024',
    location: 'London',
    website: 'https://mistral.ai',
  },
  {
    id: 'harvey',
    name: 'Harvey',
    type: 'venture',
    sector: 'Legal / Legaltech',
    stage: 'series-c',
    hcGrowthPct: 48,
    valuation: 3,
    marketCap: null,
    cultureScore: 4.3,
    employeeCount: 200,
    openRoles: 25,
    techStack: ['Python', 'TypeScript', 'Go'],
    investors: ['OpenAI', 'Sequoia', 'GV'],
    engBlogUrl: null,
    lastRound: 'Series C · Dec 2024',
    location: 'San Francisco Bay Area',
    website: 'https://harvey.ai',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    type: 'venture',
    sector: 'Developer Tools',
    stage: 'series-e',
    hcGrowthPct: 11,
    valuation: 3.25,
    marketCap: null,
    cultureScore: 4.3,
    employeeCount: 600,
    openRoles: 29,
    techStack: ['TypeScript', 'Rust', 'Go', 'Next.js'],
    investors: ['Accel', 'GV', 'Tiger Global'],
    engBlogUrl: 'https://vercel.com/blog/category/engineering',
    lastRound: 'Series E · May 2023',
    location: 'Remote-first',
    website: 'https://vercel.com',
  },
  {
    id: 'wiz',
    name: 'Wiz',
    type: 'venture',
    sector: 'Cybersecurity',
    stage: 'series-e',
    hcGrowthPct: 35,
    valuation: 12,
    marketCap: null,
    cultureScore: 4.4,
    employeeCount: 1800,
    openRoles: 54,
    techStack: ['Go', 'Python', 'TypeScript'],
    investors: ['Sequoia', 'Index Ventures', 'Lightspeed'],
    engBlogUrl: 'https://www.wiz.io/blog/tag/engineering',
    lastRound: 'Series E · May 2024',
    location: 'New York City',
    website: 'https://wiz.io',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    type: 'public',
    sector: 'Cloud Infra',
    stage: 'public',
    hcGrowthPct: 9,
    valuation: null,
    marketCap: 38,
    cultureScore: 4.2,
    employeeCount: 6800,
    openRoles: 82,
    techStack: ['Go', 'Python', 'Java', 'Rust'],
    investors: ['Public (NASDAQ: DDOG)'],
    engBlogUrl: 'https://www.datadoghq.com/blog/engineering/',
    lastRound: 'IPO · Sep 2019',
    location: 'New York City',
    website: 'https://datadoghq.com',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    type: 'public',
    sector: 'Data / Analytics',
    stage: 'public',
    hcGrowthPct: -6,
    valuation: null,
    marketCap: 41,
    cultureScore: 3.8,
    employeeCount: 7200,
    openRoles: 43,
    techStack: ['Java', 'C++', 'Python', 'Go'],
    investors: ['Public (NYSE: SNOW)'],
    engBlogUrl: 'https://www.snowflake.com/blog/category/engineering/',
    lastRound: 'IPO · Sep 2020',
    location: 'San Francisco Bay Area',
    website: 'https://snowflake.com',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    type: 'public',
    sector: 'Cybersecurity',
    stage: 'public',
    hcGrowthPct: 13,
    valuation: null,
    marketCap: 32,
    cultureScore: 4.1,
    employeeCount: 4100,
    openRoles: 67,
    techStack: ['Rust', 'Go', 'TypeScript', 'C++'],
    investors: ['Public (NYSE: NET)'],
    engBlogUrl: 'https://blog.cloudflare.com',
    lastRound: 'IPO · Sep 2019',
    location: 'San Francisco Bay Area',
    website: 'https://cloudflare.com',
  },
  {
    id: 'palantir',
    name: 'Palantir',
    type: 'public',
    sector: 'AI / ML',
    stage: 'public',
    hcGrowthPct: 7,
    valuation: null,
    marketCap: 220,
    cultureScore: 3.5,
    employeeCount: 3800,
    openRoles: 28,
    techStack: ['Java', 'TypeScript', 'Python', 'Go'],
    investors: ['Public (NYSE: PLTR)'],
    engBlogUrl: 'https://blog.palantir.com',
    lastRound: 'DPO · Sep 2020',
    location: 'New York City',
    website: 'https://palantir.com',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    type: 'public',
    sector: 'Developer Tools',
    stage: 'public',
    hcGrowthPct: -4,
    valuation: null,
    marketCap: 7.5,
    cultureScore: 4.4,
    employeeCount: 2100,
    openRoles: 15,
    techStack: ['Ruby', 'Go', 'Vue.js', 'PostgreSQL'],
    investors: ['Public (NASDAQ: GTLB)'],
    engBlogUrl: 'https://about.gitlab.com/blog/categories/engineering/',
    lastRound: 'IPO · Oct 2021',
    location: 'Remote-first',
    website: 'https://gitlab.com',
  },
];
